spring:
  datasource:
    url: jdbc:mysql://10.42.129.142:3306/22jy0126
    username: 22jy0126
    password: 22jy0126
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  mybatis:
    mapper-locations: com.hikariSchool.mapper.*
